project:
  type: website
  pre-render: custom2qmd.py

website:
  title: "qblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto