project:
  type: website
  pre-render: custom2qmd.py
  post-render:
    - notes2site.py
    - app2site.py
  preview: 
      host: '0.0.0.0'
      port: 3000
      browser: false
  # twitter-card: true

website:
  title: "Rahul Saraf"
  site-url: 'https://qblog.zealmaker.com'
  site-path: '/'
  navbar:
    right:
      - blog.qmd
      - app.qmd
      - notes/index.qmd
      - icon: github
        href: https://github.com/Rahuketu86
      - icon: twitter
        href: https://twitter.com/rahuketu86
    
format:
  html:
    theme: yeti
    css: styles.css
  
execute:
  freeze: auto
